builders:
  graphql_codegen:
    import: 'package:graphql_switch/builder.dart'
    builder_factories: ['SwitchBuilder.builder']
    build_extensions: {'$lib$': ['.graphql.dart']}
    auto_apply: dependents
    build_to: source
    applies_builders: ['json_serializable']
    runs_before: ['json_serializable']
